apiVersion: v1
kind: Service
metadata:
  name: sda-validator-orchestrator
  labels:
    app: sda-validator-orchestrator
spec:
  ports:
    - name: api
      port: 8080
      targetPort: api
      protocol: TCP
  selector:
    app: sda-validator-orchestrator
