apiVersion: apps/v1
kind: Deployment
metadata:
  name: sda-validator-orchestrator
  labels:
    app: sda-validator-orchestrator
spec:
  selector:
    matchLabels:
      app: sda-validator-orchestrator
  template:
    metadata:
      labels:
        app: sda-validator-orchestrator
    spec:
      initContainers:
        - name: validator-downloader
          image: golang:1.25-alpine
          command: [ "/bin/sh", "-c" ]
          args:
            - wget -O /validators/100-200_word_validator.sif https://raw.githubusercontent.com/neicnordic/sensitive-data-archive/refs/heads/feature/validator-orchestrator-prototype/sda-validator/apptainer-example/100-200_word_validator.sif;
          volumeMounts:
            - name: validators
              mountPath: /validators
      containers:
        - name: sda-validator-orchestrator
          image: ghcr.io/neicnordic/sensitive-data-archive/sda-validator/orchestrator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PORT
              value: "8080"
            - name: VALIDATOR_PATHS
              value: "/validators/100-200_word_validator.sif"
            - name: SDA_API_URL
              value: "http://pipeline-sda-svc-api.default:8080"
            - name: SDA_API_TOKEN
              value: ""
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          volumeMounts:
            - name: validators
              mountPath: /validators/
      volumes:
        - name: validators
          emptyDir: {}
