apiVersion: v1
kind: ConfigMap
metadata:
  name: sda-validator-orchestrator-rbac
data:
  rbac.json: |-
    {
      "policy": [
        {
          "role": "admin",
          "path": "/admin/*",
          "action": "(GET)|(POST)"
        }, {
          "role": "submission",
          "path": "/validators",
          "action": "GET"
        }, {
          "role": "submission",
          "path": "/validate",
          "action": "POST"
        }, {
          "role": "submission",
          "path": "/result",
          "action": "(GET)"
        }
      ],
      "roles": [
        {
          "role": "admin",
          "rolebinding": "submission"
        },
        {
          "role": "testu@lifescience-ri.eu",
          "rolebinding": "admin"
        }, {
          "role": "requester@demo.org",
          "rolebinding": "admin"
        }
      ]
      
    
    }
