version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker images across services
  - package-ecosystem: docker
    directories:
      - "/postgresql"
      - "/rabbitmq"
      - "/sda-validator/orchestrator"
      - "/sda"
      - "/sda-download"
      - "/sda-sftp-inbox"
      - "/sda-doa"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directories:
      - "/sda-validator/orchestrator"
      - "/sda"
      - "/sda-download"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/sda-sftp-inbox"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/sda-doa"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - "*"

## release v1 branch
  - package-ecosystem: "github-actions"
    target-branch: release_v1
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "[release_v1]"

  - package-ecosystem: docker
    target-branch: release_v1
    directories:
      - "/postgresql"
      - "/rabbitmq"
      - "/sda"
      - "/sda-download"
      - "/sda-sftp-inbox"
      - "/sda-doa"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "[release_v1]"

  - package-ecosystem: maven
    target-branch: release_v1
    directory: "/sda-doa"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - "*"
    commit-message:
      prefix: "[release_v1]"

  - package-ecosystem: maven
    target-branch: release_v1
    directory: "/sda-sftp-inbox"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - "*"
    commit-message:
      prefix: "[release_v1]"

  - package-ecosystem: gomod
    target-branch: release_v1
    directories:
      - "/sda"
      - "/sda-download"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
    commit-message:
      prefix: "[release_v1]"
