default: true

# Allow arbitrary line length
#
# Reason: We apply the one-sentence-per-line rule. A sentence may get longer than 80 characters, especially if links are contained.
#
# Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
MD013: false

# Allow duplicate headings
#
# Reasons:
#
# - The chosen option is considerably often used as title of the decision record (e.g., "Use MADR 4.0.0" appears in both the title and the decision outcome).
# - We use "Examples" or similar headings multiple times in some records.
# - Markdown lint should support the user and not annoy them.
#
# Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content
MD024: false
