#!/bin/sh
# Creates the Crypt4GH file that the download v2 integration tests are seeded
# with. Runs in the credentials container after make_download_credentials.sh,
# which provides /shared/crypt4gh and the key pair the reencrypt service opens.
set -e

# Encryption is randomised, so a rerun on a kept volume must reuse the files
# from the first run: the archived body has to match the seeded header.
if [ -f /shared/testfile.env ]; then
    echo "download v2 test file already exists"
    exit 0
fi

python - <<'EOF'
import hashlib
import os
import struct
import subprocess

# Deterministic plaintext spanning many 64 KiB crypt4gh segments, with a
# partial last segment.
size = 3 * 1024 * 1024 + 1234
stream = b"".join(hashlib.sha256(b"sda-download-v2 %d" % i).digest() for i in range(size // 32 + 1))
plaintext = stream[:size]
with open("/shared/testfile", "wb") as f:
    f.write(plaintext)

# The CLI exits 0 even when it fails, so drop output from an interrupted run
# and check the result below. "y" confirms the autogenerated sender key.
if os.path.exists("/shared/testfile.c4gh"):
    os.remove("/shared/testfile.c4gh")
subprocess.run(
    ["/shared/crypt4gh", "encrypt", "-p", "/shared/c4gh.pub.pem", "-f", "/shared/testfile"],
    input=b"y\n",
    check=True,
)
with open("/shared/testfile.c4gh", "rb") as f:
    encrypted = f.read()

# Header: magic, version and packet count, then packets that each start with
# their length (little-endian uint32, counting the length field itself).
magic, version, packets = encrypted[:8], *struct.unpack("<II", encrypted[8:16])
assert magic == b"crypt4gh" and version == 1, "not a crypt4gh v1 file"
header_size = 16
for _ in range(packets):
    header_size += struct.unpack("<I", encrypted[header_size:header_size + 4])[0]
header, body = encrypted[:header_size], encrypted[header_size:]
# Each 64 KiB plaintext segment gains a 12-byte nonce and a 16-byte MAC.
assert len(body) == size + 28 * -(-size // 65536), "encrypted body has the wrong size"

# Ingest archives the header-stripped body and stores the header in the database.
with open("/shared/testfile.body", "wb") as f:
    f.write(body)
with open("/shared/testfile.sha256", "w") as f:
    f.write(hashlib.sha256(plaintext).hexdigest())

# Sourced by the database seed. Written last and renamed into place, so it
# only exists once the rest does.
with open("/shared/testfile.env.tmp", "w") as f:
    f.write(f"TESTFILE_HEADER={header.hex()}\n")
    f.write(f"TESTFILE_SIZE={len(plaintext)}\n")
    f.write(f"TESTFILE_SHA256={hashlib.sha256(plaintext).hexdigest()}\n")
    f.write(f"TESTFILE_MD5={hashlib.md5(plaintext).hexdigest()}\n")
    f.write(f"TESTFILE_BODY_SIZE={len(body)}\n")
    f.write(f"TESTFILE_BODY_SHA256={hashlib.sha256(body).hexdigest()}\n")
os.replace("/shared/testfile.env.tmp", "/shared/testfile.env")

print(f"download v2 test file: {len(plaintext)} bytes plaintext, {header_size} bytes header, {len(body)} bytes body")
EOF
