services:

  db:
    user: postgres
    container_name: db
    environment:
      - NOTLS=true
      - POSTGRES_PASSWORD=rootpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-postgres
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/data

  database_user_creation:
    container_name: database_user_creation
    image: postgres:15.4-alpine
    command:
      - "/bin/sh"
      - "-c"
      - |
        pg_isready 
        psql -U postgres -h db -d sda -c "ALTER ROLE download LOGIN PASSWORD 'download';"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=rootpassword

  s3:
    command: server /data
    container_name: s3
    environment:
      - MINIO_ROOT_USER=access
      - MINIO_ROOT_PASSWORD=secretkey
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    healthcheck:
      test: ["CMD", "curl", "-fq", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: minio/minio
    ports:
      - "9000:9000"

  createbucket:
    container_name: buckets
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set add s3 http://s3:9000 access secretkey;
      /usr/bin/mc mb s3/archive;
      exit 0;
      "
    restart: on-failure

  download:
    command: sda-download
    container_name: download
    depends_on:
      database_user_creation:
        condition: service_completed_successfully
      s3:
        condition: service_healthy
      mockauth:
        condition: service_healthy
    environment:
      - ARCHIVE_URL=http://s3
      - ARCHIVE_TYPE=s3
      - DB_HOST=db
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-download
    build:
      context: ..
    volumes:
      - ./config-notls.yaml:/config.yaml
      - ./:/dev_utils/
      - ./archive_data/4293c9a7-dc50-46db-b79a-27ddc0dad1c6:/tmp/4293c9a7-dc50-46db-b79a-27ddc0dad1c6
    mem_limit: 256m
    ports:
      - "8080:8080"
    restart: always

  download-unencrypted:
    command: sda-download
    container_name: download-unencrypted
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      mockauth:
        condition: service_healthy
    environment:
      - ARCHIVE_URL=http://s3
      - ARCHIVE_TYPE=s3
      - DB_HOST=db
      - C4GH_TRANSIENTKEYPATH=/dev_utils/c4gh.sec.pem
      - C4GH_TRANSIENTPASSPHRASE=oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-download
    build:
      context: ..
    volumes:
      - ./config-notls.yaml:/config.yaml
      - ./:/dev_utils/
      - ./archive_data/4293c9a7-dc50-46db-b79a-27ddc0dad1c6:/tmp/4293c9a7-dc50-46db-b79a-27ddc0dad1c6
    mem_limit: 256m
    ports:
      - "9080:8080"
    restart: always

  mockauth:
    command:
      - /bin/sh
      - -c
      - |
        apt update
        apt install curl -y
        pip install --upgrade pip
        pip install aiohttp Authlib
        python -u /mockoidc.py
    container_name: mockauth
    image: python:3.10-slim
    healthcheck:
      test: [ "CMD", "curl", "-fkq", "http://localhost:8000/.well-known/openid-configuration" ]
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - ./mockoidc/mockoidc.py:/mockoidc.py
    mem_limit: 256m
    ports:
      - "8000:8000"
    restart: always

  reencrypt:
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}
    build: ../../sda/
    command: [ sda-reencrypt ]
    container_name: reencrypt
    ports:
      - "50051:50051"
    restart: always
    volumes:
      - ./config-notls.yaml:/config.yaml
      - ./:/dev_utils/

volumes:
  archive:
