version: "2.4"
services:
  certfixer:
    command:
      - /bin/sh
      - -c
      - |
        cp /origcerts/* /certs
        chown -R nobody:nobody /certs/*
        chmod -R og-rw /certs/*-key.pem
        chown -R 70:70 /certs/db*
        ls -la /certs/

    container_name: certfixer
    image: alpine:latest
    volumes:
      - ./certs:/origcerts
      - certs:/certs
  db:
    user: postgres
    container_name: db
    depends_on:
      - certfixer
    environment:
      - PKI_VOLUME_PATH=/certs/
      - PG_CA=/var/lib/postgresql/tls/ca.pem
      - PG_SERVER_CERT=/var/lib/postgresql/tls/db.pem
      - PG_SERVER_KEY=/var/lib/postgresql/tls/db-key.pem
      - POSTGRES_PASSWORD=rootpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-postgres
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/data
      - certs:/var/lib/postgresql/tls/
  database_user_creation:
    container_name: database_user_creation
    image: postgres:15.4-alpine
    command:
      - "/bin/sh"
      - "-c"
      - |
        pg_isready 
        psql -U postgres -h db -d sda -c "ALTER ROLE download LOGIN PASSWORD 'download';"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=rootpassword
  s3:
    command: server /data
    container_name: s3
    environment:
      - MINIO_ROOT_USER=access
      - MINIO_ROOT_PASSWORD=secretkey
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    healthcheck:
      test: ["CMD", "curl", "-fkq", "https//localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./certs/ca.pem:/root/.minio/certs/CAs/public.crt
      - ./certs/s3.pem:/root/.minio/certs/public.crt
      - ./certs/s3-key.pem:/root/.minio/certs/private.key
  createbucket:
    container_name: buckets
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set s3 https://s3:9000 access secretkey;
      /usr/bin/mc mb s3/archive;
      exit 0;
      "
    volumes:
      - ./certs/ca.pem:/etc/ssl/certs/public.crt
    restart: always
  download:
    command: sda-download
    container_name: download
    depends_on:
      - certfixer
      - database_user_creation
      - mockauth
    env_file: ./env.download
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-download
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
      - ./iss.json:/iss.json
      - certs:/dev_utils/certs
      - ./archive_data/4293c9a7-dc50-46db-b79a-27ddc0dad1c6:/tmp/4293c9a7-dc50-46db-b79a-27ddc0dad1c6
    mem_limit: 256m
    ports:
      - "8443:8443"
    restart: always
  mockauth:
    command:
      - /bin/sh
      - -c
      - |
        apt update
        apt install curl -y
        pip install --upgrade pip
        pip install aiohttp Authlib
        python -u /mockoidc.py
    container_name: mockauth
    healthcheck:
      test: [ "CMD", "curl", "-fkq", "https://localhost:8000/.well-known/openid-configuration" ]
      interval: 10s
      timeout: 30s
      retries: 10
    image: python:3.11-slim
    volumes:
      - ./mockoidc/mockoidc.py:/mockoidc.py
      - certs:/certs
    mem_limit: 256m
    ports:
      - "8000:8000"
    restart: always

volumes:
  archive:
  certs:
