/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// nolint
package openapi

import (
	"github.com/gin-gonic/gin"
)

type ValidatorOrchestratorAPI interface {

	// AdminResultGet Get /admin/result
	AdminResultGet(c *gin.Context)

	// AdminValidatePost Post /admin/validate
	AdminValidatePost(c *gin.Context)

	// ResultGet Get /result
	ResultGet(c *gin.Context)

	// ValidatePost Post /validate
	ValidatePost(c *gin.Context)

	// ValidatorsGet Get /validators
	ValidatorsGet(c *gin.Context)
}
