/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidateRequest struct {

	// The file paths to be validated
	FilePaths []string `json:"file_paths,omitempty"`

	// The validators to be executed
	Validators []string `json:"validators,omitempty"`
}
