/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// nolint
package openapi

type ValidatePost200Response struct {

	// The validation id
	ValidationId string `json:"validation_id,omitempty"`
}
