client-name: "aai-auth-evil"
client-id: "auth-evil"
client-secret: "oauqnbcuzyg"
redirect-uris: ["http://localhost:8802/oidc/login"]
token-endpoint-auth-method: "client_secret_basic"
scope: ["openid", "profile", "email", "ga4gh_passport_v1", "eduperson_entitlement"]
grant-types: ["authorization_code"]
post-logout-redirect-uris: ["http://localhost:8801/oidc/login"]