#!/bin/bash
docker build \
       --cache-from egarchive/lega-mq:stable \
       --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
       --build-arg SOURCE_COMMIT=$(git rev-parse --short HEAD) \
       --tag $IMAGE_NAME .
