{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if eq "s3" .Values.global.inbox.storageType }}
{{- if not .Values.global.vaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-auth
type: Opaque
data:
  {{- if and (ne "" .Values.global.oidc.id) (ne "" .Values.global.oidc.secret) }}
  oidcID: {{ .Values.global.oidc.id | quote | trimall "\"" | b64enc }}
  oidcSecret: {{ .Values.global.oidc.secret | quote | trimall "\"" | b64enc }}
  {{- end }}
  {{- if or ( eq "federated" .Values.global.schemaType) ( eq "" .Values.global.schemaType) }}
  cegaID: {{ .Values.global.cega.user | quote | trimall "\"" | b64enc }}
  cegaSecret: {{ .Values.global.cega.password | quote | trimall "\"" | b64enc }}
  {{- end }}
  dbPassword: {{ required "DB password is required" (include "dbPassAuth" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserAuth" .) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
