{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if .Values.global.download.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-download
  labels:
    role: download
    app: {{ template "sda.fullname" . }}-download
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ template "sda.fullname" . }}-download
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.download.replicaCount }}
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.fullname" . }}-download
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.fullname" . }}-download
        role: download
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.global.vaultSecrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/download-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.download.annotations }}
{{- toYaml .Values.download.annotations | nindent 8 -}}
{{- end }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
        topologyKey: kubernetes.io/hostname
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "sda.fullname" . }}-download
            topologyKey: kubernetes.io/hostname
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 65534 
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: download
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}-download"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"
        command: ["sda-download"]
        env:
        - name: CONFIGFILE
          value: {{ include "confFile" . }}
        ports:
        - name: download
          containerPort: {{ ternary 8443 8080 .Values.global.tls.enabled }}
          protocol: TCP
        livenessProbe:
{{ toYaml .Values.download.livenessProbe | trim | indent 10 }}
        readinessProbe:
{{ toYaml .Values.download.readinessProbe | trim | indent 10 }}
        resources:
{{ toYaml .Values.download.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.vaultSecrets }}
        - name: config
          mountPath: {{ template "configPath" . }}
        {{- if .Values.global.download.serveDecrypted.c4ghKeyFile }}
        - name: c4gh-transient
          mountPath: {{ template "c4ghPath" . }}
        {{- end }}
        - name: iss
          mountPath: {{ template "trustedIssPath" . }}
      {{- end }}
      {{- if and (not .Values.global.pkiService) .Values.global.tls.enabled }}
        - name: tls
          mountPath: {{ template "tlsPath" . }}
      {{- end }}
      {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.archive.volumePath | quote }}
      {{- end }}
      enableServiceLinks: false
      volumes:
      {{- if and (not .Values.global.pkiService) .Values.global.tls.enabled }}
        - name: tls
        {{- if or .Values.global.tls.clusterIssuer .Values.global.tls.issuer }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-download-certs
        {{- else }}
          secret:
            defaultMode: 0440
            secretName: {{ required "An certificate issuer or a TLS secret name is required for download" .Values.download.tls.secretName }}
        {{- end }}
      {{- end }}
      {{- if not .Values.global.vaultSecrets }}
        - name: config
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-download
        {{- if .Values.global.download.serveDecrypted.c4ghKeyFile }}
        - name: c4gh-transient
          secret:
            defaultMode: 0440
            secretName: {{ required "A secret for the transient c4gh key is required" .Values.global.download.serveDecrypted.secretName }}
            items:
            - key: {{ .Values.global.download.serveDecrypted.c4ghKeyFile }}
              path: {{ .Values.global.download.serveDecrypted.c4ghKeyFile }}
        {{- end }}
        - name: iss
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-download-iss
            items:
            - key: {{ .Values.global.download.trusted.configFile }}
              path: {{ .Values.global.download.trusted.configFile }}
      {{- end }}
      {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
        {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
        {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
{{- end }}
{{- end }}
