{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if .Values.global.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-mapper
  labels:
    app: {{ template "sda.fullname" . }}-mapper
spec:
  ports:
  - name: prometheus
    port: 9090
    targetPort: prometheus
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-mapper
{{- end }}
{{- end }}
