{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-rotatekey
type: Opaque
stringData:
  config.yaml: |-
    broker:
      host: {{ required "A valid MQ host is required" .Values.global.broker.host }}
      port: {{ default (ternary 5671 5672 .Values.global.tls.enabled) .Values.global.broker.port }}
      user: {{ required "MQ user is required" (include "mqUserRotate" .) }}
      password: {{ required "MQ password is required" (include "mqPassRotate" .) }}
      vhost: {{ include "brokerVhost" . }}
      exchange: {{ default "sda" .Values.global.broker.exchange }}
      routingKey: {{ default "rotate" .Values.rotatekey.routingKey }}
    db:
      host: {{ .Values.global.db.host }}
      port: {{ .Values.global.db.port }}
      user: {{ required "DB user is required" (include "dbUserRotate" .) }}
      password: {{ required "DB password is required" (include "dbPassRotate" .) }}
      database: {{ .Values.global.db.name }}
      sslmode: {{ ternary .Values.global.db.sslMode "disable" .Values.global.tls.enabled }}
    c4gh:
      # This matches the rotatePubKeyPath from your integration test config
      rotatePubKeyPath: {{ template "c4ghPath" . }}/{{ .Values.global.c4gh.rotatePubKey }}
      privateKeys:
      {{- range .Values.global.c4gh.privateKeys }}
      - filePath: {{ template "c4ghPath" . }}/{{ .filePath }}
        passphrase: {{ .passphrase | quote }}
      {{- end }}
    grpc:
      host: {{ template "sda.fullname" . }}-reencrypt
      port: {{ ternary 50443 50051 .Values.global.tls.enabled }}
    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}
{{- end }}
{{- end }}
