{{- if and .Values.global.c4gh.rotatePubKeyData .Values.global.tls.enabled (not .Values.global.pkiService) }}
{{- if or .Values.global.tls.clusterIssuer .Values.global.tls.issuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "sda.fullname" . }}-rotatekey-certs
spec:
  secretName: {{ template "sda.fullname" . }}-rotatekey-certs

  duration: 2160h # 90d

  commonName: {{ template "sda.fullname" . }}-rotatekey
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
  dnsNames:
    - {{ template "sda.fullname" . }}-rotatekey
    - {{ template "sda.fullname" . }}-rotatekey.{{ .Release.Namespace }}.svc
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ template "TLSissuer" . }}
    kind: {{ ternary "Issuer" "ClusterIssuer" (empty .Values.global.tls.clusterIssuer )}}
    group: cert-manager.io
{{- end -}}
{{- end -}}