{{- if .Values.global.c4gh.rotatePubKeyData }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if .Values.global.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-rotatekey
  labels:
    app: {{ template "sda.fullname" . }}-rotatekey
spec:
  ports:
  - name: prometheus
    port: 9090
    targetPort: prometheus
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-rotatekey
{{- end }}
{{- end }}
{{- end }}
