{{- if .Values.global.c4gh.rotatePubKeyData }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-rotatekey
type: Opaque
stringData:
  config.yaml: |-
    broker:
    {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{- if .Values.global.broker.verifyPeer }}
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
      {{- end }}
    {{- end }}
      exchange: {{ default "sda" .Values.global.broker.exchange }}
      host: {{ required "A valid MQ host is required" .Values.global.broker.host }}
      port: {{ default (ternary 5671 5672 .Values.global.tls.enabled) .Values.global.broker.port }}
      prefetchCount: {{ default 2 .Values.global.broker.prefetchCount }}
      password: {{ required "MQ password is required" (include "mqPassRotate" .) }}
      queue: {{ default "rotatekey" .Values.global.broker.rotateKeyQueue }}
    {{- if ne "" ( default "" .Values.global.broker.serverName ) }}
      serverName: {{ .Values.global.broker.serverName }}
    {{- end }}
      ssl: {{ .Values.global.tls.enabled }}
      user: {{ required "MQ user is required" (include "mqUserRotate" .) }}
      {{- if .Values.global.tls.enabled }}
      verifyPeer: {{ .Values.global.broker.verifyPeer }}
      {{- end }}
      vhost: {{ include "brokerVhost" . }}

    database:
    {{- if .Values.global.tls.enabled }}
      ca_cert: {{ template "tlsPath" . }}/ca.crt
      client_cert: {{ template "tlsPath" . }}/tls.crt
      client_key: {{ template "tlsPath" . }}/tls.key
    {{- end }}
      host: {{ .Values.global.db.host }}
      name: {{ .Values.global.db.name }}
      password: {{ required "DB password is required" (include "dbPassRotate" .) }}
      port: {{ .Values.global.db.port }}
      ssl_mode: {{ ternary .Values.global.db.sslMode "disable" .Values.global.tls.enabled }}
      user: {{ required "DB user is required" (include "dbUserRotate" .) }}

    grpc:
      host: {{ required "A valid grpc host is required" .Values.global.reencrypt.host }}
      port: {{ ternary 50443 50051 .Values.global.tls.enabled }}
      timeout: {{ default 30 .Values.global.reencrypt.timeout }}
      {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
      {{- end }}

    c4gh:
      rotatePubKeyPath: {{ template "configPath" . }}/target-key.pub

    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}

  target-key.pub: {{ required "global.c4gh.rotatePubKeyData is required" .Values.global.c4gh.rotatePubKeyData | b64dec | quote }}

{{- end }}
{{- end }}
{{- end }}