{{- include "sda.detectLegacyStorageKeys" . }}
{{- if not .Values.global.vaultSecrets }}
{{- if not (empty .Values.global.archive.s3) }}
{{- $arc := index .Values.global.archive.s3 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3archive-keys
type: Opaque
data:
  s3ArchiveAccessKey: {{ required "global.archive.s3[0].accessKey is required" $arc.accessKey | quote | trimall "\"" | b64enc }}
  s3ArchiveSecretKey: {{ required "global.archive.s3[0].secretKey is required" $arc.secretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if not (empty .Values.global.backupArchive.s3) }}
{{- $bk := index .Values.global.backupArchive.s3 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3backup-keys
type: Opaque
data:
  s3BackupAccessKey: {{ required "global.backupArchive.s3[0].accessKey is required" $bk.accessKey | quote | trimall "\"" | b64enc }}
  s3BackupSecretKey: {{ required "global.backupArchive.s3[0].secretKey is required" $bk.secretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if not (empty .Values.global.inbox.s3) }}
{{- $ib := index .Values.global.inbox.s3 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3inbox-keys
type: Opaque
data:
  s3InboxAccessKey: {{ required "global.inbox.s3[0].accessKey is required" $ib.accessKey | quote | trimall "\"" | b64enc }}
  s3InboxSecretKey: {{ required "global.inbox.s3[0].secretKey is required" $ib.secretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if and .Values.global.c4gh.publicKeyData (first .Values.global.c4gh.privateKeys).keyData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.c4gh.secretName }}
type: Opaque
data:
  {{ .Values.global.c4gh.publicKey }}: {{ .Values.global.c4gh.publicKeyData }}
{{- range $pk := .Values.global.c4gh.privateKeys }}
  {{- if and $pk.keyName $pk.keyData $pk.passphrase }}
  {{ $pk.keyName }}: {{ $pk.keyData }}
  {{- end }}
{{- end }}
  {{- if and .Values.global.c4gh.syncPubKey .Values.global.c4gh.syncPubKeyData }}
  {{ .Values.global.c4gh.syncPubKey }}: {{ .Values.global.c4gh.syncPubKeyData }}
  {{- end }}
{{- end }}
{{- end }}
