{{- if eq "isolated" .Values.global.schemaType }}
{{- if ne "" .Values.global.sync.remote.host }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if .Values.global.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-sync
  labels:
    app: {{ template "sda.fullname" . }}-sync
spec:
  ports:
  - name: prometheus
    port: 9090
    targetPort: prometheus
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-sync
{{- end }}
{{- end }}
{{- end }}
{{- end }}
