{{- if eq "isolated" .Values.global.schemaType }}
{{- if and (ne "" .Values.global.sync.api.password) (ne "" .Values.global.sync.api.user) }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-syncapi
type: Opaque
stringData:
  config.yaml: |-
    broker:
    {{- if .Values.global.tls.enabled }}
      caCert: {{ template "tlsPath" . }}/ca.crt
      {{- if .Values.global.broker.verifyPeer }}
      clientCert: {{ template "tlsPath" . }}/tls.crt
      clientKey: {{ template "tlsPath" . }}/tls.key
      {{- end }}
    {{- end }}
      exchange: {{ default "sda" .Values.global.broker.exchange }}
      host: {{ required "A valid MQ host is required" .Values.global.broker.host }}
      port: {{ default (ternary 5671 5672 .Values.global.tls.enabled) .Values.global.broker.port }}
      prefetchCount: {{ default 1 .Values.global.broker.prefetchCount }}
      password: {{ required "MQ password is required" (include "mqPassMapper" .) }}
      queue: {{ default "mappings" .Values.global.broker.finalizeQueue }}
    {{- if ne "" ( default "" .Values.global.broker.serverName ) }}
      serverName: {{.Values.global.broker.serverName }}
    {{- end }}
      ssl: {{ .Values.global.tls.enabled }}
      user: {{ required "MQ user is required" (include "mqUserMapper" .) }}
    {{- if .Values.global.tls.enabled }}
      verifyPeer: {{ .Values.global.broker.verifyPeer }}
    {{- end }}
      vhost: {{ include "brokerVhost" . }}
    log:
      format: {{ .Values.global.log.format }}
      level: {{ .Values.global.log.level }}
    {{- if .Values.global.tls.enabled }}
    server:
      cert: {{ template "tlsPath" . }}/tls.crt
      key: {{ template "tlsPath" . }}/tls.key
    {{- end }}
    sync:
      api:
        password: {{ required "sync API password is required" .Values.global.sync.api.password }}
        user: {{ required "sync API user is required" .Values.global.sync.api.user }}
      brokerQueue: {{ default "mapping_stream" .Values.global.sync.brokerQueue }}
      centerPrefix: {{ .Values.global.sync.centerPrefix }}
      remote:
        host: {{ required "remote sync API host is required" .Values.global.sync.remote.host }}
        password: {{ required "remote sync API password is required" .Values.global.sync.remote.password }}
        port: {{ .Values.global.sync.remote.port }}
        user: {{ required "remote sync API user is required" .Values.global.sync.remote.user }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
