/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ValidatorAPI interface {


    // ValidatePost Post /validate
     ValidatePost(c *gin.Context)

    // ValidatorsGet Get /validators
     ValidatorsGet(c *gin.Context)

}