/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidateResponseInner struct {

	// Name of the validator this result reefers to
	Validator string `json:"validator,omitempty"`

	// Completed / Failed, denotes if the validation was executed successfully or not
	Result string `json:"result,omitempty"`

	Files []ValidateResponseInnerFilesInner `json:"files,omitempty"`

	Messages []ValidateResponseInnerFilesInnerMessagesInner `json:"messages,omitempty"`
}
