/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidateResponseInnerFilesInner struct {

	// Id of the file
	Id string `json:"id,omitempty"`

	// Path of the file
	Path string `json:"path,omitempty"`

	// Success / Failure, denotes if the validation was successful or failed
	Result string `json:"result,omitempty"`

	Messages []ValidateResponseInnerFilesInnerMessagesInner `json:"messages,omitempty"`
}
