/*
 * SDA validator orchestrator API
 *
 * This is the API for the validator orchestrator.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidateResponseInnerFilesInnerMessagesInner struct {

	// Level of message
	Level string `json:"level,omitempty"`

	// Timestamp of message
	Time string `json:"time,omitempty"`

	// Message
	Message string `json:"message,omitempty"`
}
