log:
  format: "json"
  level: "debug"
admin:
  users: "requester@demo.org"
archive:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "archive"
  region: "us-east-1"

auth:
  cega:
    authUrl: "http://cega-nss:8443/username/"
    id:
    secret:
  infoText: "About service text"
  infoURL: "http://example.org/about"
  jwt:
    issuer: "https://auth:8888"
    privateKey: /shared/keys/jwt.key
    signatureAlg: ES256
    tokenTTL: 168
  publicFile: "/shared/c4gh.pub.pem"
  resignJwt:
  s3Inbox: "http://inbox:8000"

backup:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "sync-inbox"
  region: "us-east-1"
inbox:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "inbox"
  region: "us-east-1"

broker:
  host: "rabbitmq"
  port: "5672"
  user: ""
  password: ""
  vhost: "/sda"
  exchange: "sda"
  routingKey: ""
  ssl: "false"

db:
  host: "postgres"
  port: "5432"
  user: ""
  password: ""
  database: "sda"
  sslmode: "disable"

c4gh:
  filePath: /shared/c4gh.sec.pem
  passphrase: "c4ghpass"
  syncPubKeyPath: /shared/sync.pub.pem

oidc:
  id:
  jwkPath: /jwk
  provider: http://oidc:8080
  redirectUrl: http://auth_oidc:8080/oidc/login
  secret:
reencrypt:
  host: reencrypt

server:
  cert: ""
  key: ""
  jwtpubkeypath: "/shared/keys/pub/"
  jwtpubkeyurl: "http://oidc:8080/jwk"

sync:
  api:
    password: "pass"
    user: "user"
  centerPrefix: "aa"
  destination:
    type: "s3"
    url: "http://s3"
    port: 9000
    readypath: "/minio/health/ready"
    accessKey: "access"
    secretKey: "secretKey"
    bucket: "sync-inbox"
    region: "us-east-1"
  remote:
    host: "http://sync-api"
    port: "8080"
    password: "pass"
    user: "user"

schema:
  type: "bigpicture"
