name: Release sda-admin

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Ensure main or hotfix branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"

          echo "Branch: $BRANCH"
          
          if [[ "$BRANCH" != "main" && ! "$BRANCH" =~ ^hotfix/ ]]; then
            echo "Workflow may only run on:"
            echo "  - main"
            echo "  - hotfix/*"
            exit 1
          fi

      - name: Validate target version
        env:
          TARGET_VERSION: ${{ inputs.version }}
        run: |
          set -euo pipefail
          
          # Validate target version format
          if ! [[ "$TARGET_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+([.-][A-Za-z0-9]+)*)?$ ]]; then
            echo "$TARGET_VERSION: Version must match MAJOR.MINOR.PATCH[-suffix]"
            exit 1
          fi
          
          CHANGELOG_VERSION=$(
            grep -E '^## \[[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+([.-][A-Za-z0-9]+)*)?\]' sda-admin/CHANGELOG.md \
            | head -n1 \
            | sed -E 's/^## \[([0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+([.-][A-Za-z0-9]+)*)?)\].*/\1/'
          )
          
          if [ -z "$CHANGELOG_VERSION" ]; then
            echo "Could not determine current version from the sda-admin/CHANGELOG.md"
            exit 1
          fi
          
          if [ "$CHANGELOG_VERSION" != "${TARGET_VERSION}" ]; then
            echo "Latest version in changelog is $CHANGELOG_VERSION, target version is ${TARGET_VERSION}"
            exit 1
          fi
          
          UNRELEASED_CONTENT=$(
            awk '
            /^## \[Unreleased\]/ { in_section=1; next }
            /^## \[/ && in_section { exit }
            in_section { print }
            ' sda-admin/CHANGELOG.md
          )
          
          # Remove blank lines and whitespace
          UNRELEASED_CONTENT_CLEAN=$(echo "$UNRELEASED_CONTENT" | sed '/^[[:space:]]*$/d')
          
          if [ -n "$UNRELEASED_CONTENT_CLEAN" ]; then
            echo "Unreleased section is not empty"
            exit 1
          fi
          
          CONTENT_TO_BE_RELEASED=$(
            awk "
            /^## \[${TARGET_VERSION}\]/ { in_section=1; next }
            /^## \[/ && in_section { exit }
            in_section { print }
            " sda-admin/CHANGELOG.md
          )
          
          # Remove blank lines and whitespace
          CONTENT_TO_BE_RELEASED_CLEAN=$(echo "$CONTENT_TO_BE_RELEASED" | sed '/^[[:space:]]*$/d')
          
          if [ -z "$CONTENT_TO_BE_RELEASED_CLEAN" ]; then
            echo "Changelog entry for ${TARGET_VERSION} is empty"
            exit 1
          fi

      - name: Create and push tag
        env:
          TARGET_VERSION: ${{ inputs.version }}
        run: |
          git tag "sda-admin-${TARGET_VERSION}"
          git push origin "sda-admin-${TARGET_VERSION}"

      - name: Extract release notes
        env:
          TARGET_VERSION: ${{ inputs.version }}
        run: |
          awk "
            /^## \\[${TARGET_VERSION}\\]/ { in_section=1; next }
            /^## \\[/ && in_section { exit }
            in_section { print }
          " sda-admin/CHANGELOG.md > RELEASE_NOTES.md

      - name: Draft release
        uses: softprops/action-gh-release@v3
        with:
          name: sda-admin-${{ inputs.version }}
          tag_name: "sda-admin-${{ inputs.version }}"
          make_latest: false
          generate_release_notes: false
          body_path: RELEASE_NOTES.md
          draft: true

  package:
    needs: [ prepare_release ]
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List of GOOS and GOARCH pairs from `go tool dist list`
        goosarch:
          - "linux/amd64"
          - "windows/amd64"
          - "darwin/amd64"
          - "darwin/arm64"
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v6
        with:
          ref: sda-admin-${{ inputs.version }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.22'
        id: go

      - name: Get dependencies
        run: |
          cd sda-admin
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Get OS and arch info
        env:
          VERSION: ${{ inputs.version }}
        run: |
          GOOSARCH=${{ matrix.goosarch }}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=sda-admin_${VERSION}_${GOOS}_${GOARCH}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

      - name: Build
        if: ${{ matrix.goosarch != 'windows/amd64' }}
        env:
          VERSION: ${{ inputs.version }}
        run: |
          cd sda-admin
          go build -o "$BINARY_NAME" -v -ldflags="-s -w -X 'main.version=${VERSION}'"
          tar -czf "$BINARY_NAME.tgz" "$BINARY_NAME" ../LICENSE
          echo "ARTIFACT"="$BINARY_NAME.tgz" >> $GITHUB_ENV

      - name: Build windows
        if: ${{ matrix.goosarch == 'windows/amd64' }}
        env:
          VERSION: ${{ inputs.version }}
        run: |
          cd sda-admin
          go build -o "$BINARY_NAME" -v -ldflags="-s -w -X 'main.version=${VERSION}'"
          zip "$BINARY_NAME.zip" "$BINARY_NAME" ../LICENSE
          echo "ARTIFACT"="$BINARY_NAME.zip" >> $GITHUB_ENV

      - name: Upload artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "sda-admin-${{ inputs.version }}" "sda-admin/${{ env.ARTIFACT }}"

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          name: sda-admin-${{ inputs.version }}
          tag_name: "sda-admin-${{ inputs.version }}"
          make_latest: false
          generate_release_notes: false
